### ISSUE TITLE
OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by xudh777** [qijiezhao/M2Det#100]
1 1080ti 
pytorch1.0
run demo.py

pos:(-inf,-1624725.8,nan,-1624725.8), ids:hair_drier, score:1.000
pos:(-inf,-inf,nan,nan), ids:hair_drier, score:1.000
Traceback (most recent call last):
  File "/home/xdh/YOLOvsSSD/M2Det-master/demo.py", line 150, in <module>
    im2show = draw_detection(image, boxes, scores, cls_inds, fps)
  File "/home/xdh/YOLOvsSSD/M2Det-master/demo.py", line 70, in draw_detection
    box = [int(_) for _ in box]
  File "/home/xdh/YOLOvsSSD/M2Det-master/demo.py", line 70, in <listcomp>
    box = [int(_) for _ in box]
OverflowError: cannot convert float infinity to integer

**Comment by dyx118186878** [comment]
i got the same problem  when i train my own model in VOCdataset  ,and when i test my model  this happened

**Comment by xudh777** [comment]
I've given up. The authorities are no longer upholding it.

**Comment by zt0910** [comment]
i got the same problem when i train my own model in own data,anyone has idea to do ?
