### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by Youggie** [qijiezhao/M2Det#110]
Traceback (most recent call last):
  File "/usr/lib/pycharm-community/helpers/pydev/pydevd.py", line 1596, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/lib/pycharm-community/helpers/pydev/pydevd.py", line 974, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/lib/pycharm-community/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/disk2/syj/code/M2Det/train.py", line 98, in <module>
    loss_l, loss_c = criterion(out, priors, targets)
  File "/disk2/syj/anaconda2/envs/M2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/disk2/syj/code/M2Det/layers/modules/multibox_loss.py", line 108, in forward
    loss_c = F.cross_entropy(conf_p, targets_weighted, reduction='sum')
  File "/disk2/syj/anaconda2/envs/M2/lib/python3.7/site-packages/torch/nn/functional.py", line 1551, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/disk2/syj/anaconda2/envs/M2/lib/python3.7/site-packages/torch/nn/functional.py", line 975, in log_softmax
    return input.log_softmax(dim)
RuntimeError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by weqvr** [comment]
i  meet the same problem . your torch vision is ?

**Comment by weqvr** [comment]
I  resolve this problem by changing the torchvison to 1.3.

**Comment by TianshengSun** [comment]
@weqvr do you mean update torch from 0.4 to 1.3?

**Comment by Willert98** [comment]
meet the same problem +1

**Comment by idnihai** [comment]
meet the problem
