### ISSUE TITLE
Why adjust_learning_rate() only refers to step_lr of COCO?

### ISSUE THREAD

**Issue by yushi-okuinishi** [qijiezhao/M2Det#113]
https://github.com/qijiezhao/M2Det/blob/de4a6241bf22f7e7f46cb5cb1eb95615fd0a5e12/utils/core.py#L73-L80

When I tried to train  with resume_epoch=300, I got the following error because max(step_lr) of COCO was 200.
`Traceback (most recent call last):  
  File "train.py", line 330, in <module>  
    lr = adjust_learning_rate(optimizer, cfg.train_cfg.gamma, epoch, step_index, iteration, epoch_size, cfg)  
  File "/opt/program/utils/core.py", line 95, in adjust_learning_rate  
    param_group['lr'] = lr`  

I think **if cfg.train_cfg.step_lr.COCO[i]>=epoch** was False, and lr wasn't defined.

Should we make it compatible with VOC dataset?

**Comment by wangshaobobetter** [comment]
change the"COCO" to "VOC"
