### ISSUE TITLE
interpolate

### ISSUE THREAD

**Issue by wwfnwg** [qijiezhao/M2Det#47]

**Comment by ShiqiLi047** [comment]
Traceback (most recent call last):
  File "demo.py", line 109, in <module>
    out = net(img)
  File "/data8T/lsq/anaconda3/envs/pytorch/lib/python3.5/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/data8T/lsq/detection/M2Det/m2det.py", line 112, in forward
    (self.reduce(base_feats[0]), F.interpolate(self.up_reduce(base_feats[1]),scale_factor=2,mode='nearest')),1
AttributeError: module 'torch.nn.functional' has no attribute 'interpolate'
**我也是这个问题，你有解决吗？**

**Comment by imyhxy** [comment]
版本问题吧，我的pytorch==1.0.1.post2没有问题
