### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ModuleList:

### ISSUE THREAD

**Issue by chaogeSDK** [qijiezhao/M2Det#51]
the completed error message:
Loading base network...
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    init_net(net, cfg, args.resume_net) # init the network with pretrained weights or resumed weights
  File "/data/M2Det/utils/core.py", line 39, in init_net
    net.init_model(cfg.model.pretrained)
  File "/data/M2Det/m2det.py", line 155, in init_model
    self.base.load_state_dict(base_weights)
  File "/data/ananconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ModuleList:
        Missing key(s) in state_dict: "0.weight", "0.bias", "2.weight", "2.bias", "5.weight", "5.bias", "7.weight", "7.bias", "10.weight", "10.bias", "12.weight", "12.bias", "14.weight", "14.bias", "17.weight", "17.bias",......
**can anyone help me?**

**Comment by JankYang12** [comment]
Aye, I have met the same problem, and I solved it.
The first: you must modify the code of "**m2det.py**" , line **155**
the orignal code in line 155:   self.base.load_state_dict(base_weights)
modified code:   self.load_state_dict({k.replace('module.',''):v for k,v in torch.load(base_model_path).items()})

**Comment by JankYang12** [comment]
if you find out of memory then, just tun the bath_size smaller.
