### ISSUE TITLE
demo.py in windows

### ISSUE THREAD

**Issue by machineCYC** [qijiezhao/M2Det#63]
When I run python demo.py -c=configs/m2det512_vgg.py -m=weights/m2det512_vgg.pth --show. Below error will appear. Anyone know how to fix?

Traceback (most recent call last):
  File "demo.py", line 6, in <module>
    from utils.nms_wrapper import nms
  File "d:\workspace\M2Det\utils\nms_wrapper.py", line 8, in <module>
    from .nms.cpu_nms import cpu_nms, cpu_soft_nms
ModuleNotFoundError: No module named 'utils.nms.cpu_nms'

**Comment by yiwa6520** [comment]
I face the same question with you. I guess, it is caused by failed compiling the make.sh file. Did you find the way to compile make.sh in Windows?

**Comment by machineCYC** [comment]
yap! it is. But I change the os to Ubuntu18.04, it works.

On the other hand, I will try to modify some code in build.py, but it still not work for me.
