### ISSUE TITLE
train my own dataset

### ISSUE THREAD

**Issue by Tuyota** [qijiezhao/M2Det#68]
when I train my own datasets,
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    images, targets = next(batch_iterator)
  File "/home/zhushiwei/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/zhushiwei/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/zhushiwei/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/zhushiwei/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/zhushiwei/M2Det/data/voc0712.py", line 178, in __getitem__\n    target = self.target_transform(target)\n  File "/home/zhushiwei/M2Det/data/voc0712.py", line 129, in __call__\n    label_idx = self.class_to_ind[name]\nKeyError: \'vehicle\'\n'
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f33d2830f28>>
Traceback (most recent call last):
  File "/home/zhushiwei/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
  File "/home/zhushiwei/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
  File "/home/zhushiwei/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
AttributeError: Can't get attribute 'KeyError' on None
looking forward for your reply.

**Comment by henbucuoshanghai** [comment]
?
