### ISSUE TITLE
problem of TypeError in data_augment

### ISSUE THREAD

**Issue by ZhuofeiKang** [qijiezhao/M2Det#74]
===> Constructing M2Det model
Loading base network...
Initializing weights for [tums, reduce, up_reduce, leach, loc, conf]...
===> Loading Dataset...
loading annotations into memory...
Done (t=9.01s)
creating index...
index created!
train2017 gt roidb loaded from /home/travail/mx-rcnn-master/data/cache/coco_train2017_roidb.pkl
===> Training M2Det on COCO
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    images, targets = next(batch_iterator)
  File "/home/travail/miniconda3/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/travail/miniconda3/envs/torch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: Traceback (most recent call last):
  File "/home/travail/miniconda3/envs/torch/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/travail/miniconda3/envs/torch/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/travail/M2Det/data/coco.py", line 160, in __getitem__
    img, target = self.preproc(img, target)
  File "/home/travail/M2Det/data/data_augment.py", line 171, in __call__
    boxes = targets[:,:-1].copy()
TypeError: unhashable type: 'slice'

I have met this problem when I train the model. Could you help me?
Thank you!

**Comment by xiaoshulinlove** [comment]
+1
