### ISSUE TITLE
I would like to learn using the original data set

### ISSUE THREAD

**Issue by 16j5021** [qijiezhao/M2Det#78]
I want to learn using original data set, not coco,voc
If you know the procedure please let me know
Or please tell me the website that describes it
I think that the file of config and the file of train are made exclusively for coco,voc

**Comment by fukumame** [comment]
Hi, I forked original repository and am customizing it to be able to train original dataset now.

https://github.com/AillisInc/M2Det

The structure of the original data set is the same as the Pascal VOC format.

**Pascal VOC format**
[Directory structure](https://docs.supervise.ly/import/local_files/pascal_voc/)
[Annotation XML](https://gist.github.com/Prasad9/30900b0ef1375cc7385f4d85135fdb44)

You can specify the path of root directory and imageset name as command line option.
https://github.com/AillisInc/M2Det/blob/a0c9ce7895eed560f60ef787c4df8748d6672a59/train.py#L16-L18

The example code to train original dataset is like this

```bash
python train.py --dataset general --image_set trainval --roor_dir /path/to/root_dir
```

The definition of general dataset is as follows.
https://github.com/AillisInc/M2Det/blob/master/data/general_image_dataset.py

This code works well in my environment.
But I don't validate this code enough, so please tell me if any problems occur.

Thank you.

**Comment by fukumame** [comment]
And also you can specify a class name of each object at config file like this
https://github.com/AillisInc/M2Det/blob/a0c9ce7895eed560f60ef787c4df8748d6672a59/configs/m2det320_resnet101.py#L16

**Comment by 16j5021** [comment]
Thank you for your answer.
I will try it.
I will post if there is a problem.

**Comment by 16j5021** [comment]
Such an error occurs when executing train.
The 'dog' part of the Value error changes each time you run it.
Do you know the solution?



$ python train.py --dataset general --image_set trainval -rd /home/***/***/M2Det/VOCdevkit
----------------------------------------------------------------------
|                       M2Det Training Program                       |
----------------------------------------------------------------------
===> Constructing M2Det model ['yellow', 'bold']
Initializing weights for [tums, reduce, up_reduce, leach, loc, conf]...
Epoch 0 started!
  0%|                                          | 0/361 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 111, in <module>
    main(cfg)
  File "train.py", line 84, in main
    for i, data in enumerate(tqdm(data_loader)):
  File "/home/***/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1022, in __iter__
    for obj in iterable:
  File "/home/***/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 582, in __next__
    return self._process_next_batch(batch)
  File "/home/***/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 608, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/***/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/***/anaconda3/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 99, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/***/***/M2Det/data/general_image_dataset.py", line 35, in __getitem__
    target = self._transform_target(target)
  File "/home/***/***/M2Det/data/general_image_dataset.py", line 62, in _transform_target
    label_idx = self.class_names.index(name)
ValueError: 'dog' is not in list

**Comment by fukumame** [comment]
@16j5021 
Did you define `dogs` label(object name) in a list of the below line?

https://github.com/fukumame/M2Det/blob/a0c9ce7895eed560f60ef787c4df8748d6672a59/configs/m2det320_resnet101.py#L16

You need to define all the label to be detected.
These label is define at the tag of <object> <name> in annotation XML 

As a matter of course, if you will use another config file such as `configs/m2det320_vgg.py`, you need to edit an appropriate file not the above one.

**Comment by 16j5021** [comment]
Thank you for your answer.
I will try to do it.

**Comment by devendraswamy** [comment]
> Hi, I forked original repository and am customizing it to be able to train original dataset now.
> 
> https://github.com/fukumame/M2Det
> 
> The structure of the original data set is the same as the Pascal VOC format.
> 
> **Pascal VOC format**
> [Directory structure](https://docs.supervise.ly/import/local_files/pascal_voc/)
> [Annotation XML](https://gist.github.com/Prasad9/30900b0ef1375cc7385f4d85135fdb44)
> 
> You can specify the path of root directory and imageset name as command line option.
> https://github.com/AillisInc/M2Det/blob/a0c9ce7895eed560f60ef787c4df8748d6672a59/train.py#L16-L18
> 
> The example code to train original dataset is like this
> 
> ```shell
> python train.py --dataset general --image_set trainval --roor_dir /path/to/root_dir
> ```
> 
> The definition of general dataset is as follows.
> https://github.com/AillisInc/M2Det/blob/master/data/general_image_dataset.py
> 
> This code works well in my environment.
> But I don't validate this code enough, so please tell me if any problems occur.
> 
> Thank you.

Your are done a great work and i had a doubt , i had a dataset like .csv file and that csv file contain data like in the format of """"  FILEPATH , XMIN , YMIN , XMAX , YMAX , CLASS ''''' . for  train the model with that csv file , what i need to modify ? 

kindly help me!!

Thanking you !!

**Comment by s-hijiri0311** [comment]
Such an error occurs when I run demo.py by my original dataset.


python demo.py -c=configs/m2det512_vgg.py -m=results/m2det_snapshot_e0.pt 
 ----------------------------------------------------------------------
|                       M2Det Demo Program                             |
 ----------------------------------------------------------------------
===> Constructing M2Det model
Loading resume network...
Traceback (most recent call last):
  File "demo.py", line 144, in <module>
    boxes = allboxes[:,:4]
IndexError: too many indices for array


please, help me!

**Comment by temps1101** [comment]
I think the M2Det detected too many boxes. This happens when your model is not trained. Maybe, you might have to train more.
