### ISSUE TITLE
Training of m2det800_vgg

### ISSUE THREAD

**Issue by KimiakiShirahama** [qijiezhao/M2Det#79]
I'm now trying to train m2det800_vgg (i.e. configs/m2det800_vgg.py), but I have the error below. Can someone give me an advice to solve this error? For your information, I'm using a single RXT 2080Ti and could successfully train m2det512_vgg (i.e. configs/m2det512_vgg.py) by just following the instruction on the git repository.

Traceback (most recent call last):
  File "train.py", line 88, in <module>
    loss_l, loss_c = criterion(out, priors, targets)
  File "/home/sakata/anaconda3/envs/m2detv3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/sakata/M2Det/layers/modules/multibox_loss.py", line 108, in forward
    loss_c = F.cross_entropy(conf_p, targets_weighted, reduction='sum')
  File "/home/sakata/anaconda3/envs/m2detv3/lib/python3.6/site-packages/torch/nn/functional.py", line 2056, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/sakata/anaconda3/envs/m2detv3/lib/python3.6/site-packages/torch/nn/functional.py", line 1871, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: invalid argument 2: non-empty vector or matrix expected at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu:31

**Comment by earlysleepearlyup** [comment]
hello,I've encountered the same problem. Have you solved it?

**Comment by weqvr** [comment]
hello,i also met this problem.have you solved it ?and your torch vision is ?
