### ISSUE TITLE
train.py error 

### ISSUE THREAD

**Issue by siyuan13180892817** [qijiezhao/M2Det#86]
CUDA_VISIBLE_DEVICES=1 python train.py --resume_net=weights/vgg16_reducedfc.pth

----------------------------------------------------------------------
|                       M2Det Training Program                       |
----------------------------------------------------------------------
===> Constructing M2Det model
Loading resume network...
===> Loading Dataset...
<data.voc0712.VOCDetection object at 0x7f21b506d940>
===> Training M2Det on VOC
--------------out net(images) processing-----------
Traceback (most recent call last):
  File "train.py", line 92, in <module>
    out = net(images)
  File "/home/huangsiyuan/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huangsiyuan/M2Det/M2Det-master/m2det.py", line 120, in forward
    self.leach[i](base_feature), tum_outs[i-1][-1]
  File "/home/huangsiyuan/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huangsiyuan/M2Det/M2Det-master/layers/nn_utils.py", line 88, in forward
    deconved_feat[i], self.latlayer[i](conved_feat[len(self.layers)-1-i])
  File "/home/huangsiyuan/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huangsiyuan/M2Det/M2Det-master/layers/nn_utils.py", line 19, in forward
    x = self.conv(x)
  File "/home/huangsiyuan/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/huangsiyuan/anaconda3/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory
Exception ignored in: <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7f21b506dda0>>
Traceback (most recent call last):
  File "/home/huangsiyuan/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 399, in __del__
  File "/home/huangsiyuan/anaconda3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 378, in _shutdown_workers
  File "/home/huangsiyuan/anaconda3/lib/python3.6/multiprocessing/queues.py", line 337, in get
AttributeError: Can't get attribute 'Tensor' on None

**Comment by siyuan13180892817** [comment]
How to slove this problem?

**Comment by siyuan13180892817** [comment]
batch size问题  需要设置的小一点

**Comment by cyishun1125** [comment]
Are you using m2det320_vgg16.py?
Where can I get it?
