### ISSUE TITLE
Could you provide the pretrained weights?

### ISSUE THREAD

**Issue by SoarAnyway** [qijiezhao/M2Det#95]
thanks for your work. I notice that in the config files you add pretrained weights name as 'weights/vgg16_reducedfc.pth', how can I get this weights? 
I try used m2det512_vgg.pth but run wrong as follow:
Loading base network...
Traceback (most recent call last):
  File "train.py", line 37, in <module>
    init_net(net, cfg, args.resume_net) # init the network with pretrained weights or resumed weights
  File "/home/share/kuangwenteng/M2Det-master/utils/core.py", line 39, in init_net
    net.init_model(cfg.model.pretrained)
  File "/home/share/kuangwenteng/M2Det-master/m2det.py", line 155, in init_model
    self.base.load_state_dict(base_weights)
  File "/home/ubuntu/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ModuleList:
	Missing key(s) in state_dict: "0.weight", "0.bias", "2.weight", "2.bias", "5.weight", "5.bias", "7.weight", "7.bias", "10.weight", "10.bias", "12.weight", "12.bias", "14.weight", "14.bias", "17.weight", "17.bias", "19.weight", "19.bias", "21.weight", "21.bias", "24.weight", "24.bias", "26.weight", "26.bias", "28.weight", "28.bias", "31.weight", "31.bias", "33.weight", "33.bias".

**Comment by kuwt** [comment]
You can find it in https://github.com/amdegroot/ssd.pytorch
